name: bmtree
channels:
  - defaults
dependencies:
  - appdirs=1.4.4=pyh9f0ad1d_0
  - blas=1.0=mkl
  - blosc=1.21.0=he49afe7_0
  - brotli=1.0.9=h0d85af4_5
  - brotli-bin=1.0.9=h0d85af4_5
  - brotlipy=0.7.0=py37h271585c_1001
  - brunsli=0.1=h046ec9c_0
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.17.2=h0d85af4_0
  - ca-certificates=2021.5.30=h033912b_0
  - cairo=1.16.0=h0ab9d94_1001
  - certifi=2021.5.30=py37hf985489_0
  - cffi=1.14.6=py37hda351d9_0
  - cfitsio=3.470=h389770f_2
  - chardet=4.0.0=py37hf985489_1
  - charls=2.2.0=h046ec9c_0
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.7=py37hce4a858_0
  - cudatoolkit=9.0=h41a26b3_0
  - cycler=0.10.0=py_2
  - cython=0.29.24=py37hd8d24ac_0
  - cytoolz=0.11.0=py37h271585c_3
  - dask-core=2021.8.1=pyhd8ed1ab_0
  - decorator=4.4.2=py_0
  - easydict=1.9=py_0
  - ffmpeg=4.0=h01ea3c9_0
  - fontconfig=2.13.1=h10f422b_1005
  - freetype=2.10.4=h4cff582_1
  - fsspec=2021.8.1=pyhd8ed1ab_0
  - future=0.18.2=py37hf985489_3
  - gettext=0.19.8.1=h7937167_1005
  - giflib=5.2.1=hbcb3906_2
  - glib=2.68.4=he49afe7_0
  - glib-tools=2.68.4=he49afe7_0
  - graphite2=1.3.13=h2e338ed_1001
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.2=hc401514_3
  - icu=58.2=h0a44026_1000
  - imagecodecs=2021.7.30=py37hf5aa8e4_0
  - imageio=2.9.0=py_0
  - intel-openmp=2019.4=233
  - jasper=2.0.14=hee3b9ff_2
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=hbcb3906_0
  - json_tricks=3.15.5=pyhd8ed1ab_0
  - jxrlib=1.1=h35c211d_2
  - kiwisolver=1.3.2=py37h737db71_0
  - krb5=1.19.2=hcfbf3a7_0
  - lcms2=2.12=h577c468_0
  - lerc=2.2.1=h046ec9c_0
  - libaec=1.0.5=he49afe7_0
  - libblas=3.9.0=8_mkl
  - libbrotlicommon=1.0.9=h0d85af4_5
  - libbrotlidec=1.0.9=h0d85af4_5
  - libbrotlienc=1.0.9=h0d85af4_5
  - libcblas=3.9.0=8_mkl
  - libcurl=7.78.0=hf45b732_0
  - libcxx=12.0.1=habf9029_0
  - libcxxabi=4.0.1=hcfea43d_1
  - libdeflate=1.8=h0d85af4_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.3=h046ec9c_2
  - libgfortran=3.0.1=0
  - libglib=2.68.4=hd556434_0
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.9.0=8_mkl
  - libnghttp2=1.43.0=h07e645a_0
  - libopencv=3.4.2=h7c891bd_1
  - libopus=1.3.1=hc929b4f_1
  - libpng=1.6.37=h7cec526_2
  - libprotobuf=3.15.8=hcf210ce_0
  - libssh2=1.10.0=h52ee1ee_0
  - libtiff=4.3.0=h1167814_0
  - libvpx=1.7.0=h378b8a2_0
  - libwebp-base=1.2.1=h0d85af4_0
  - libxml2=2.9.12=hcdb78fc_0
  - libzopfli=1.0.3=h046ec9c_0
  - llvm-openmp=12.0.1=hda6cdc1_1
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=he49afe7_1
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.4.3=py37h3147e9e_0
  - mkl=2020.4=h08c4f10_301
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.2=h2e338ed_4
  - networkx=2.5.1=pyhd8ed1ab_0
  - ninja=1.10.2=h9a9d8cb_0
  - numpy=1.21.2=py37haefe36b_0
  - numpy-base=1.18.1=py37h6575580_1
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=3.4.2=py37h6fd60c2_1
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1l=h0d85af4_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.2=py37h5b83a90_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.45=he49afe7_0
  - pillow=8.3.1=py37h76dc067_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pixman=0.38.0=h01d97ff_1003
  - pooch=1.5.1=pyhd8ed1ab_0
  - py-opencv=3.4.2=py37h7c891bd_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py37hf985489_3
  - python=3.7.10=h7728216_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.8.0=cpu_py37h0262b6d_1
  - pytorch-cpu=1.8.0=cpu_py37he781eb1_1
  - pytz=2021.1=pyhd8ed1ab_0
  - pywavelets=1.1.1=py37h37391d0_3
  - pyyaml=5.4.1=py37h271585c_1
  - readline=8.1=h05e3726_0
  - scikit-image=0.18.3=py37h5b83a90_0
  - scikit-learn=0.24.2=py37h572704e_1
  - scipy=1.2.1=py37hbd7caa9_1
  - setuptools=57.4.0=py37hf985489_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h35c211d_1
  - snappy=1.1.8=hb1e8313_3
  - sqlite=3.36.0=h23a322b_0
  - tensorboardx=2.0=py_0
  - threadpoolctl=2.2.0=pyh8a188c0_0
  - tifffile=2021.8.30=pyhd8ed1ab_0
  - tk=8.6.11=h5dbffcc_1
  - toolz=0.11.1=py_0
  - torchvision=0.10.0=py37he4a07f4_0_cpu
  - tornado=6.1=py37h271585c_1
  - tqdm=4.62.2=pyhd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=haf1e3a3_1
  - yacs=0.1.6=py_0
  - yaml=0.2.5=haf1e3a3_0
  - zfp=0.5.5=he49afe7_5
  - zlib=1.2.11=h7795811_1010
  - zstd=1.5.0=h582d3a0_0
  - pip:
    - aiohttp==3.7.4.post0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - anyio==3.3.1
    - appnope==0.1.2
    - argcomplete==1.12.3
    - argon2-cffi==21.1.0
    - async-timeout==3.0.1
    - attrs==21.2.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.1.0
    - blessings==1.7
    - cachetools==4.2.2
    - click==8.0.1
    - debugpy==1.4.3
    - defusedxml==0.7.1
    - entrypoints==0.3
    - filelock==3.0.12
    - google-api-core==1.30.0
    - google-auth==1.32.1
    - googleapis-common-protos==1.53.0
    - gpustat==0.6.0
    - grpcio==1.38.1
    - hilbertcurve==2.0.5
    - hiredis==2.0.0
    - idna==2.10
    - importlib-metadata==4.6.1
    - ipykernel==6.4.1
    - ipython==7.27.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==3.0.1
    - json5==0.9.6
    - jsonschema==3.2.0
    - jupyter-client==7.0.2
    - jupyter-core==4.7.1
    - jupyter-server==1.11.0
    - jupyterlab==3.1.11
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.8.1
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - msgpack==1.0.2
    - multidict==5.1.0
    - nbclassic==0.3.1
    - nbclient==0.5.4
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.3
    - numpy-hilbert-curve==1.0.1
    - nvidia-ml-py3==7.352.0
    - opencensus==0.7.13
    - opencensus-context==0.1.2
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.20
    - protobuf==3.17.3
    - psutil==5.8.0
    - psycopg2-binary==2.9.3
    - ptyprocess==0.7.0
    - py-spy==0.3.7
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.8.2
    - pygments==2.10.0
    - pyrsistent==0.18.0
    - pyzmq==22.2.1
    - pyzorder==0.0.1
    - ray==1.4.1
    - redis==3.5.3
    - requests==2.25.1
    - requests-unixsocket==0.2.0
    - rsa==4.7.2
    - send2trash==1.8.0
    - sniffio==1.2.0
    - terminado==0.12.1
    - testpath==0.5.0
    - traitlets==5.1.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.1
    - yarl==1.6.3
    - zipp==3.5.0
